// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Xe2Vy2mfhpgITdre-dgLJF6jx6sh6EA',
    appId: '1:500182865164:web:73696ab91f823a31eca529',
    messagingSenderId: '500182865164',
    projectId: 'lab-firebase-9a63a',
    authDomain: 'lab-firebase-9a63a.firebaseapp.com',
    storageBucket: 'lab-firebase-9a63a.appspot.com',
    measurementId: 'G-17RCBYHPQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvqawOlpyQpOzXAB6Ozgr-tNBVmhA1qvY',
    appId: '1:500182865164:android:26739b0b91009da6eca529',
    messagingSenderId: '500182865164',
    projectId: 'lab-firebase-9a63a',
    storageBucket: 'lab-firebase-9a63a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VjNJHVT5xb7VY9o3RxBLl0mx5-0vXRs',
    appId: '1:500182865164:ios:abeebb28445c131feca529',
    messagingSenderId: '500182865164',
    projectId: 'lab-firebase-9a63a',
    storageBucket: 'lab-firebase-9a63a.appspot.com',
    iosBundleId: 'com.example.labFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5VjNJHVT5xb7VY9o3RxBLl0mx5-0vXRs',
    appId: '1:500182865164:ios:abeebb28445c131feca529',
    messagingSenderId: '500182865164',
    projectId: 'lab-firebase-9a63a',
    storageBucket: 'lab-firebase-9a63a.appspot.com',
    iosBundleId: 'com.example.labFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Xe2Vy2mfhpgITdre-dgLJF6jx6sh6EA',
    appId: '1:500182865164:web:4ba8257b40e537d1eca529',
    messagingSenderId: '500182865164',
    projectId: 'lab-firebase-9a63a',
    authDomain: 'lab-firebase-9a63a.firebaseapp.com',
    storageBucket: 'lab-firebase-9a63a.appspot.com',
    measurementId: 'G-MD4RPD6MJP',
  );
}
